name: crocosign
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pdf: ^3.10.4
  printing: ^5.11.0
  flutter_to_pdf: ^0.1.1
  lottie: ^2.6.0
  im_stepper: ^1.0.1+1
  flutter_snake_navigationbar: ^0.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/